services:
  order-service:
    build:
      context: ./order-service
    image: order-service
    container_name: order-service
    ports:
      - "8082:8082"
    networks:
      - my-network

  product-service:
    build:
      context: ./product-service
    image: product-service
    container_name: product-service
    ports:
      - "8081:8081"
    networks:
      - my-network

  api-gateway:
    build:
      context: ./api-gateway
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - order-service
      - product-service
    networks:
      - my-network

  service-discovery:
    image: service-discovery
    container_name: service-discovery
    ports:
      - "8761:8761"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge