spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
